### ISSUE TITLE
Missing Typings for Event Hooks in HTML Template

### ISSUE THREAD

**Issue by JordanW9232** [ghiscoding/angular-markdown-editor#40]
### Describe the bug

None of the event hooks have proper typings when used in a HTML template. When using an event hook in html like `(onChange)="onMarkdownChange($event)"` it is not recognized and will show the following message:
```
Event onChange is not emitted by any applicable directives nor by angular-markdown-editor element
```

Although this message is shown, everything still compiles successfully and my function still works as expected, so this is only an issue with typings.

### Reproduction

Use an event hook like `(onChange)="onMarkdownChange($event)"`

### Environment Info

```shell
Angular 15.2.2
Angular-Markdown-Editor 3.0.2
Typescript 4.9.5
Windows 11
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/angular-markdown-editor/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-markdown-editor/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/angular-markdown-editor/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/angular-markdown-editor/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Custom Events are always showing errors in recent Angular versions within HTML templates and I never found how to fix this kind of issue (I'm not sure it's even possible because of Angular-Language-Service). For example, similar a similar issue was opened in another lib of mine (Angular-Slickgrid), see this [discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions/815), There are 2 things you can do to, you can either cast to `$any($event)` in the HTML template or change your function argument as `CustomEvent` and then cast the argument to the necessary interface, again see this [discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions/815) for more info. It would be great if Angular could ever provide instructions on how to fix it

I'm going to close this issue as "not doable", unless you know how to fix this, if it's even possible

**Comment by JordanW9232** [comment]
I think I may actually see the fix. I'll try making a new fork and see what I can come with. If I figure something out I could create a pull request.

**Comment by JordanW9232** [comment]
@ghiscoding I managed to figure this out and made a pull request for this here: https://github.com/ghiscoding/angular-markdown-editor/pull/41.

**Comment by JordanW9232** [comment]
I read that discussion again that you sent and I should mention that I use Webstorm, not VS Code. So the IDE may just behave differently than that Angular Language Service extension that you mentioned.
