### ISSUE TITLE
Create editor in Javascript

### ISSUE THREAD

**Issue by rizplate** [ghiscoding/angular-markdown-editor#8]
I want to convert a regular div into editor when I click a button , similar to "markdown-editable" defined in the bootstrap-markdown. 
1. Can I do it via using your module?
2. Can I use markdown-editable in your module?
3. i.e. something like this in javascript 
```
$("#someid").markdown({autofocus:false,savable:false});
```

**Comment by ghiscoding** [comment]
Sorry I was away in vacations for the past few weeks. To answer your questions however:

1. I don't know `markdown-editable`, what I used is all desribed in the [README - Dependencies](https://github.com/ghiscoding/angular-markdown-editor)
2. As mentioned, I have never tried `markdown-editable`, but I would probably say `no` since I use [bootstrap-markdown](http://www.codingdrama.com/bootstrap-markdown/) which has it's own interface. If the answer is really `no`, then I would suggest you to make your own package of the best tool set, just like I did.
3. Going back to point 2) and `bootstrap-markdown` having it's own interface, the answer again here is probably `no`. The available options/hooks/events are available under the [bootstrap-markdown](http://www.codingdrama.com/bootstrap-markdown/) site. 

Unless you think this is doable with current code (or if you submit a PR), I'm unfortunately thinking of possibly closing this issue.

**Comment by rizplate** [comment]
Thanks for reply, Sorry I think I was not clear. 

1. ```markdown-editable``` is a feature of bootstrap-markdown. If you search this term on http://www.codingdrama.com/bootstrap-markdown/ you can find it. I was just wondering if it is exposed using your angular directive.

2. Aside form point 1) My question is actually simple, even without exposing above feature. can I dynamically add this angular-markdown-editor to a div via JS i.e. if I click a button , can I run some JS to convert an empty div and convert it into markdown-editor . i.e. change a div by initializing editor at button click.  ```$("#someid").markdown({autofocus:false,savable:false});```

**Comment by ghiscoding** [comment]
Ah ok, but have you tried it? If I take the code from their website, it seems to work from my [plunker demo](http://plnkr.co/edit/AFxN7uiwkZlJ9OMZwXey?p=preview)

```html
<div data-provide="markdown-editable">
          <h3>This is some editable heading</h3>
          <p>Well, actually all contents within this "markdown-editable" context is really editable. Just click anywhere!</p>
</div>
```

I'm not sure about your point 2, but everything that is exposed (mainly the events/hooks) are displayed in the README. You can't really call javascript directly in Angular, unless you build an Angular Service which is not done for this package since it's only a Directive based. However, this is workable with regular Angular with something like this

```html
ON <input type="radio" id="editable_on" ng-model="editableMarkdown" value="on" ng-init="editableMarkdown = 'on'">
OFF <input type="radio" id="editable_off" ng-model="editableMarkdown" value="off">
<div data-provide="{{ editableMarkdown == 'on' ? 'markdown-editable' : ''}}" markdown-editor="{autofocus:false,savable:false}">
      <h3>This is some editable heading</h3>
      <p>Well, actually all contents within this "markdown-editable" context is really editable. Just click anywhere!</p>
</div>
```

**Comment by ghiscoding** [comment]
Closing since no feedback was provided
